import { createSlice } from "@reduxjs/toolkit";
import { getLocalStorage } from "../utils";

const source = createSlice({
    name: "source",
    initialState: {
        account: getLocalStorage("account") || {},
        users: null,
    },
    reducers: {
        setAccount: (state, action) => {
            state.account = action?.payload || getLocalStorage("account");
        },
        setUsers: (state, action) => {
            state.users = action?.payload || null;
        },
    },
});
export const { setAccount, setUsers } = source.actions;
export default source.reducer;

// {
//     NIK: 1234567890,
//     nama: "John Doe",
//     tempatLahir: "Jakarta",
//     tanggalLahir: "1990-01-01",
//     jenisKelamin: "Laki-Laki",
//     golonganDarah: "A",
//     alamat: "Jalan Contoh No. 123",
//     rt: 1,
//     rw: 2,
//     kelurahanDesa: "Kota Baru",
//     kecamatan: "Pusat Kota",
//     agama: "ISLAM",
//     statusPerkawinan: "KAWIN",
//     pekerjaan: "Pegawai Swasta",
//     kewarganegaraan: "WNI",
//     berlakuHingga: "2025-01-01",
//     pathFileKtp: "/path/to/foto1.jpg",
//     typeFileKtp: "image",
// },
// {
//     NIK: 9876543210,
//     nama: "Jane Doe",
//     tempatLahir: "Surabaya",
//     tanggalLahir: "1992-05-15",
//     jenisKelamin: "PEREMPUAN",
//     golonganDarah: "B",
//     alamat: "Jalan Contoh No. 456",
//     rt: 3,
//     rw: 4,
//     kelurahanDesa: "Cikini",
//     kecamatan: "Menteng",
//     agama: "KRISTEN",
//     statusPerkawinan: "BELUM KAWIN",
//     pekerjaan: "Wiraswasta",
//     kewarganegaraan: "WNI",
//     berlakuHingga: "2024-12-31",
//     pathFileKtp: "/path/to/foto2.jpg",
//     typeFileKtp: "image",
// },
// {
//     NIK: 1357924680,
//     nama: "Alice Smith",
//     tempatLahir: "Bandung",
//     tanggalLahir: "1985-08-20",
//     jenisKelamin: "PEREMPUAN",
//     golonganDarah: "O",
//     alamat: "Jalan Maju No. 789",
//     rt: 5,
//     rw: 6,
//     kelurahanDesa: "Taman Indah",
//     kecamatan: "Cibubur",
//     agama: "HINDU",
//     statusPerkawinan: "KAWIN",
//     pekerjaan: "Dokter",
//     kewarganegaraan: "ITAP",
//     berlakuHingga: "2023-10-15",
//     pathFileKtp: "/path/to/foto3.jpg",
//     typeFileKtp: "image",
// },
// {
//     NIK: 2468013579,
//     nama: "Bob Johnson",
//     tempatLahir: "Medan",
//     tanggalLahir: "1977-03-05",
//     jenisKelamin: "Laki-Laki",
//     golonganDarah: "AB",
//     alamat: "Jalan Sejahtera No. 101",
//     rt: 7,
//     rw: 8,
//     kelurahanDesa: "Sinar Harapan",
//     kecamatan: "Cirebon",
//     agama: "BUDHA",
//     statusPerkawinan: "KAWIN",
//     pekerjaan: "Pengusaha",
//     kewarganegaraan: "WNI",
//     berlakuHingga: "2026-05-20",
//     pathFileKtp: "/path/to/foto4.jpg",
//     typeFileKtp: "image",
// },
// {
//     NIK: 3698521470,
//     nama: "Eva Rodriguez",
//     tempatLahir: "Yogyakarta",
//     tanggalLahir: "1988-12-12",
//     jenisKelamin: "PEREMPUAN",
//     golonganDarah: "A",
//     alamat: "Jalan Damai No. 555",
//     rt: 9,
//     rw: 0,
//     kelurahanDesa: "Bumi Nyaman",
//     kecamatan: "Semarang",
//     agama: "KHONGHUCU",
//     statusPerkawinan: "KAWIN",
//     pekerjaan: "Guru",
//     kewarganegaraan: "WNA",
//     berlakuHingga: "2024-08-08",
//     pathFileKtp: "/path/to/foto5.jpg",
//     typeFileKtp: "image",
// },
